// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mladxciasujppfwnqbgn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1sYWR4Y2lhc3VqcHBmd25xYmduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4ODM2ODUsImV4cCI6MjA3MTQ1OTY4NX0.Jsoxl9S1wiWa7QVgopSgZg9hUj6OWmAJLe5yybiWR9k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});